### ISSUE TITLE
Assign with api or arm template

### ISSUE THREAD

**Issue by ghost** [ComputerNiagara/devopspertise#1]
Hi Lucas,

Is there any way to assign with api or arm template? Any advice would be appreciated.

Best,
Jasmine

**Comment by ComputerNiagara** [comment]
Hi Jasmine,

What are you trying to do specifically?


Thanks,
Luke

**Comment by ghost** [comment]
Hi Luke,

I have an ARM template (that I have created for vm provisioning) that I have to add two ASG inside this template. (Associate vm to ASG)

Thanks
Yasemen

**Comment by ComputerNiagara** [comment]
Hi Yasemen,

That is doable, I don't have any examples in this repo, but [here is a link](https://dev.to/omiossec/arm-templates-using-nsg-and-application-security-groups-in-your-azure-deployments-1one) to another website that shows how to do it. You just need to edit the ipConfigurations for the VM and associate the ASG to it.


Thanks,
Luke
